apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: hr-dashboard-pvc
  namespace: hr-dashboard

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
